### ISSUE TITLE
GitHub插件下载失败

### ISSUE THREAD

**Issue by TimeRainStarSky** [realhuhu/py-plugin#2]
建议把插件统一到Gitee或者使用ghproxy.com加速

**Comment by realhuhu** [comment]
我也想全弄gitee，但是有的插件容易被判别为图床，只能私有，所以有些插件只在github有

**Comment by TimeRainStarSky** [comment]
> 我也想全弄gitee，但是有的插件容易被判别为图床，只能私有，所以有些插件只在github有

那就使用ghproxy.com加速或被判为图床的部分使用压缩包
