### ISSUE TITLE
send_group_forward_msg方法无法处理messages为MessageSegment的node消息

### ISSUE THREAD

**Issue by ProblemFactory** [realhuhu/py-plugin#20]
在使用nonebot_plugin_epicfree插件时遇到了调用`py-plugin/nonebot/adapters/onebot/v11/bot.py`中`send_group_forward_msg`失败的问题。此时messages中的元素为type为node的MessageSegment类型，需要使用`i.data['nickname']`, `i.data['user_id']`和`i.data['content']`读取其中内容而不是`i['data']['name']`, `i['data']['uin']`, `i['data']['content']`

**Comment by realhuhu** [comment]
已修复
