### ISSUE TITLE
haruka_bot安装后启动出现报错

### ISSUE THREAD

**Issue by liuzj288** [realhuhu/py-plugin#24]
1.安装方式：
poetry run pip install haruka-bot

2.配置项
![image](https://user-images.githubusercontent.com/13833404/208087997-493e9760-915e-4c10-8843-d43456642e45.png)

3.报错截图
![image](https://user-images.githubusercontent.com/13833404/208088158-4228d5ce-8b01-496a-80d1-604daef08660.png)

**Comment by realhuhu** [comment]
这是哪个命令啊报错

**Comment by moshuiNW** [comment]
更新下试试？
