### ISSUE TITLE
安装后启动时报错 Error: spawn poetry ENOENT

### ISSUE THREAD

**Issue by sunyink** [realhuhu/py-plugin#26]
您好，安装完毕重启了几次后，报错一直停留如下，请问我该怎么解它，谢谢。
![QQ截图py-l 01](https://user-images.githubusercontent.com/37411580/208287441-caa287d2-ccac-4833-9907-24e725d36c2f.png)

**Comment by sunyink** [comment]
重装了node，v16.18.0→18.12.1；重装py，3.10.8→3.8.7rc1，Git为2.38.1，结果变另一个报错了
![py-21](https://user-images.githubusercontent.com/37411580/208288698-2181d82d-21b9-4931-a96d-0e26b54bfd58.png)
![py-22](https://user-images.githubusercontent.com/37411580/208288701-a08faf99-f726-4555-b3de-1441acb5bab6.png)
望指点一下 谢谢。

**Comment by realhuhu** [comment]
配置文件有问题，删掉config.yaml再启动看看

**Comment by sunyink** [comment]
> 配置文件有问题，删掉config.yaml再启动看

哇，成了，它成功启动了！~！感谢您拯救我的头发

**Comment by rebirthre** [comment]
我删了还是不行
