### ISSUE TITLE
安装好了无法启动

### ISSUE THREAD

**Issue by boli-zhazi** [realhuhu/py-plugin#3]
请问这样该怎么办
![image](https://user-images.githubusercontent.com/65220310/185879831-43187273-71e4-415e-bf4b-fb3d92eb8200.png)
![image](https://user-images.githubusercontent.com/65220310/185879931-31d5bf74-be99-448d-a4e6-6c9aac348eae.png)

**Comment by realhuhu** [comment]
ps -aux | grep "poetry run python main.py" | awk '{print $2}'|xargs kill -9
然后重启

**Comment by boli-zhazi** [comment]
还是那样。。
![image](https://user-images.githubusercontent.com/65220310/185881658-d5efcdd3-d3ec-4d9b-92f2-a722b11448b6.png)

**Comment by realhuhu** [comment]
netstat -nap | grep 50051看看

**Comment by boli-zhazi** [comment]
谢谢，是端口问题，改了个就好了
