### ISSUE TITLE
运行米游社兑换插件报错

### ISSUE THREAD

**Issue by Somnusochi** [realhuhu/py-plugin#5]
输入完cookie以后报错
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```
![image](https://user-images.githubusercontent.com/14160184/188260579-3764cd34-c76b-4320-9608-7d21ead119cc.png)
Python版本是3.9.2
<img width="794" alt="image" src="https://user-images.githubusercontent.com/14160184/188260627-a5211720-39b0-4336-a5e5-e80e68a77ea0.png">

**Comment by Zmincrix** [comment]
同
